### ISSUE TITLE
Run Ancestry sites

### ISSUE THREAD

**Issue by Phillip-a-richmond** [wassermanlab/OpenFlexTyper#23]
Ancestry sites have been produced and are on Sockeye here:

```
/scratch/st-wasserww-1/FLEXTYPER/GRCh37_Sites_Query.tsv
```

I'd like to have these run across all Polaris on Sockeye. Ideally using a new installation of openFlexTyper within:

```
/scratch/st-wasserww-1/FLEXTYPER/
```

**Comment by kounkou** [comment]
morning, ancestry results are available in /scratch/st-wasserww-1/FLEXTYPER/

**Comment by kounkou** [comment]
I launched European ancestry searches just now... I will commuinicate on slack when results are ready.

**Comment by Phillip-a-richmond** [comment]
Finished, results look good.
