### ISSUE TITLE
Results for paper

### ISSUE THREAD

**Issue by kounkou** [wassermanlab/OpenFlexTyper#39]
Hi there,

we need to generate the following number of kmers, and search them with a mono thread and a multithread strategy in indexed pathogen data to be provided by @Phillip-a-richmond : 

- [ ]           1
- [ ]         10
- [ ]       100
- [ ]     1000
- [ ]   10000
- [ ] 100000

kmers are generated from N Queries with a maximum of X Kmers per Query.

N <img src="https://latex.codecogs.com/svg.latex?\Large&space;\in"> [1; 35000] Queries
X <img src="https://latex.codecogs.com/svg.latex?\Large&space;\equiv"> 3

Number of Queries must be <img src="https://latex.codecogs.com/svg.latex?\Large&space;\geq"> 35000

Above should be repeated for kmers size : 
k <img src="https://latex.codecogs.com/svg.latex?\Large&space;\in"> {150, 125, 100, 75, 50, 31, 25}  

**Example:**
We want to generate 10 kmers and measure the query time : 

1. Take 4 queries
2. Generate **centered** kmers
    - For each query, generate 12 kmers with size: 150
    - For each query, generate 12 kmers with size: 125
    - For each query, generate 12 kmers with size: 100
    - For each query, generate 12 kmers with size: 75
    - For each query, generate 12 kmers with size: 50
    - For each query, generate 12 kmers with size: 31
    - For each query, generate 12 kmers with size: 25
3. 4 Queries will generate 4 * 3 = 12 kmers for eack kmer size, remove 2 for each
4. Search for those kmers in index in monothread and in multithread
5. provide result in a table with a number of kmers and searching Time

regards

**Comment by Phillip-a-richmond** [comment]
As you have it written above, we want to perform this for one of the WGS samples, e.g. ERR1955491. 

We also want to perform this for the pathogen query on the Patient_EBV_sequence_1000 sample, with a set of Kmers derived from the query file patho_query.tsv, selecting the EBV sequence row.

**Comment by Phillip-a-richmond** [comment]
We also want to perform the pathogen query again using the patho_query.tsv on the indexed files:

Patient_EBV_sequence_1
Patient_EBV_sequence_10
Patient_EBV_sequence_100
Patient_EBV_sequence_1000
Patient_FR751039_sequence_1
Patient_FR751039_sequence_10
Patient_FR751039_sequence_100
Patient_FR751039_sequence_1000
Patient_HIV-1_sequence_1
Patient_HIV-1_sequence_10
Patient_HIV-1_sequence_100
Patient_HIV-1_sequence_1000
Patient_U21941_sequence_1
Patient_U21941_sequence_10
Patient_U21941_sequence_100
Patient_U21941_sequence_1000

Using both the : 

- [ ] unique Kmer, and 
- [ ] max 100 appearances/kmer settings.

**Comment by Phillip-a-richmond** [comment]
Phi-X scanning of indexed RNA-seq file:

- [ ] Phil Generate Phi-X_query.tsv
- [ ] Jacques Run Phi-X query.tsv over Patient_U21941_sequence_1 index

**Comment by Phillip-a-richmond** [comment]
[Phi-X_query.txt](https://github.com/wassermanlab/OpenFlexTyper/files/3996121/Phi-X_query.txt)

**Comment by kounkou** [comment]
Jacques Run Phi-X query.tsv over Patient_U21941_sequence_1 index produces 0 results.
