### ISSUE TITLE
Lightweight example dataset included in GitHub repository

### ISSUE THREAD

**Issue by Phillip-a-richmond** [wassermanlab/OpenFlexTyper#5]
Please add an example/ directory with a pipeline that goes from fastq --> outputFlextyperCounts.tsv

The lowest hanging fruit here is a mix of simulated viral data. I've concatenated 3 viruses together (you'll have to find out which 3!) in the attached fastq, and provided the path_query.txt as well.

[MixedVirus_100_1.fq.gz](https://github.com/wassermanlab/OpenFlexTyper/files/4264294/MixedVirus_100_1.fq.gz)
[MixedVirus_100_2.fq.gz](https://github.com/wassermanlab/OpenFlexTyper/files/4264295/MixedVirus_100_2.fq.gz)
[path_query.txt](https://github.com/wassermanlab/OpenFlexTyper/files/4264300/path_query.txt)

Cheers,
Phil

**Comment by kounkou** [comment]
So the answer is :  you combined 2 sources of papillomaviruses + HIV.

```bash
gi:82503188:ref:NC_007605.1: 0 0
FR751039.1 5538 0
gi:4558520:gb:AF033819.3: 6099 0
U21941.1 5531 0
```

**Comment by Tixii** [comment]
That is not what Phil is after from this issue.

I will work on this asap once I have recovered from this horrible cold.
