### ISSUE TITLE
Data regeneration

### ISSUE THREAD

**Issue by godfrain** [wassermanlab/OpenFlexTyper#50]
Table S4, Table 1, Table 2
- [x] Starting with S4
These are non-mixed, pathogen-only samples. We use this to demonstrate the impact of parameters

- [x] Table 1
Then Table 1, this is mixing virus with a patient sample given a good configuration, 30-5, unique-yes, max_k=2000

- [x] Table 2
Then Table 2, this is multiple mixed viruses in a single patient at varying concentrations, e.g. the Patient_may etc.
This way, we show the parameters in the easiest to explain setting, then we show the single mix with our optimal config, then we show the mixed samples with multiple viral infections
For the Patient_1-5, you may have to boost the max_k_occur to 10,000 or so

**Comment by kounkou** [comment]
closing issue... all data generated
