### ISSUE TITLE
Data regeneration WGS

### ISSUE THREAD

**Issue by Phillip-a-richmond** [wassermanlab/OpenFlexTyper#51]
This has to be done for the final version of the paper. Ideally finished before final meeting with Wyeth Jan 23rd, or at least before Jan 31st submit date. 

Phil:
- [x] Regenerate ancestry query with adding chromX sites from Cytoscan beyond PAR region

Jacques:
For each in 9 Polaris samples:  
- [x] Index

--------------
- [x] ERR2304556  : ## HG02773 - Family GB58 - AFR - GWD - KID (M)
- [x] ERR1955420 : ## HG02771 - Family GB58 - AFR - GWD - FATHER
- [x] ERR1955443  :  ## HG02772 - Family GB58 - AFR - GWD - MOTHER
--------------
- [x] ERR1955404  : ### HG01682 - EUR - Family: IBS030 (Father)
- [x] ERR2304597 :  ### HG01683 - EUR - Family: IBS030 (Proband,M)
- [x] ERR1955491  : ### HG01684 - EUR - Family: IBS030 (Mother)
--------------
- [x] ERR1955507  : ## HG00662 - Family SH076 - EAS - CHS - FATHER
- [x] ERR1955495  : ## HG00663 - Family SH076 - EAS - CHS - MOTHER
- [x] ERR2304569  : ## HG00664 - Family SH076 - EAS - CHS - KID (M)
--------------

- [x] Ancestry
For 1 Polaris Sample:
- [x] CytoscanHD 

Phil:
For each in 9 Polaris Samples:  
- [x] Query --> VCF
- [x] VCF bgzip/index + merge
- [x] MergeVCF+PED --> PEDDY
- [x] New Ancestry Plots --> Fig 3

For 1 Polaris sample:
- [x] Cytoscan --> Plots for fig 3, Fig S#

**Comment by Phillip-a-richmond** [comment]
The above was finished. However, errors from the African families require re-indexing. When finished, scripts are ready to go. New to-do:

- [ ] ERR2304556 : ## HG02773 - Family GB58 - AFR - GWD - KID (M)
- [ ] ERR1955420 : ## HG02771 - Family GB58 - AFR - GWD - FATHER
- [ ] ERR1955443 : ## HG02772 - Family GB58 - AFR - GWD - MOTHER

Phil:
For each in 9 Polaris Samples:

- [ ] Query --> VCF
- [ ] VCF bgzip/index + merge
- [ ]  MergeVCF+PED --> PEDDY
- [ ]  New Ancestry Plots --> Fig 3

**Comment by kounkou** [comment]
@Phillip-a-richmond are you done with your task? Can we close this issue?
