### ISSUE TITLE
Remove Ns

### ISSUE THREAD

**Issue by kounkou** [wassermanlab/OpenFlexTyper#58]
Hi there,

```bash
./flextyper indexing -f your_file -x your_index_name -o /output_dir/ -N -D
```

where -N and -D are flags for if you want to remove Ns or Duplicates

regards

**Comment by Phillip-a-richmond** [comment]
You want to remove those parameters? Or implement them correctly?

**Comment by oriolfornes** [comment]
I would rather use option names such as “-f, —fastq-file”, “-i, —idx-prefix, —index-prefix”, “-d, —remove-dup, “-n, —remove-n”.

**Comment by Tixii** [comment]
This has been resolved in the code I fixed
.
